spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/student_db
    username: postgres
    password: wnpipkwita
    driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: create-drop
        database: postgresql
        database platform: org.hibernate.dialect.PostgreSQL10Dialect
        show-sql: true
        properties:
          hibernate:
            format-sql: false
